config/routes.rb
Rails.application.routes.draw do

  resources :food_items
  root 'home#index'

  get 'contact_us' => 'home#contact'

  get 'menu' => 'home#menu'

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoulRestaurant</title>
  <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%#= csrf_meta_tags %>

  <!-- official bootstrap -->
  <link href="bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="bootstrap/dist/css/bootstrap-theme.min.css" rel="stylesheet">

</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">SoulRestaurant</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="<%= 'active' if current_page?(root_path) %>"><a href="<%= root_path %>">Home</a>
      </li>
      <li class="dropdown <%= 'active' if current_page?(controller: 'home', action: 'menu') %>">
          <a href="home/menu" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-list-alt" area-hidden="true"></span>
            Menu
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <% @sec = Section.all %>
            <% @sec.each do |s| %>
            <li><%= link_to s.name, menu_path(id: s), class: 'btn btn-secondary' %></li>
            <% end %>
          </ul>
      </li>
      <li class="<%= 'active' if current_page?(controller: 'home', action: 'contact') %>"><%= link_to "Contact Us", controller: "home", action: "contact" %></li>
    </ul>
  </div>
</nav>
<div class="container">
<%= yield %>
</div>
<!-- official JQuery -->
<script src="jquery/dist/jquery.min.js"></script>
<script src="bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>